import { createSlice } from "@reduxjs/toolkit";

const initialState =  [
    {
      name: "ENA Chalets",
      location: "Lido di Spina, Italy",
      rating: 7.2,
      category: "house",
      type: "offering",
      country: "Italy",
      image: img1,
      description: "Чудова квартира з усіма необхідними зручностями.",
      price: "320$ за три доби",
    },
    {
      name: "AlMoIo5",
      location: "Alicante, Spain",
      rating: 6.4,
      category: "apartment",
      type: "offering",
      country: "Spain",
      image: img2,
      description: "Чудова квартира з усіма необхідними зручностями.",
      price: "320$ за три доби",
    },
    {
      name: "Just be & b",
      location: "Petrou Karakousi, Greece",
      rating: 7.8,
      category: "studio",
      type: "lookingFor",
      country: "Greece",
      image: img3,
      description: "Чудова квартира з усіма необхідними зручностями.",
      price: "320$ за три доби",
    },
    {
      name: "HOMES",
      location: "Erzhebetvaros, Budapest",
      rating: 9.2,
      category: "house",
      type: "offering",
      country: "Hungary",
      image: img4,
      description: "Чудова квартира з усіма необхідними зручностями.",
      price: "320$ за три доби",
    },
    {
      name: "Downtown Homes Relax",
      location: "Fatih, Istanbul",
      rating: 6.1,
      category: "apartment",
      type: "offering",
      country: "Turkey",
      image: img5,
      description: "Чудова квартира з усіма необхідними зручностями.",
      price: "320$ за три доби",
    },
    {
      name: "Pair of Kings",
      location: "Podgórze, Kraków",
      rating: 9.2,
      category: "house",
      type: "offering",
      country: "Poland",
      image: img6,
      description: "Чудова квартира з усіма необхідними зручностями.",
      price: "320$ за три доби",
    },
    {
      name: "Design Apartment In Party",
      location: "Rudolfsheim-Fünfhaus, Vienna",
      rating: 6.7,
      category: "apartment",
      type: "offering",
      country: "Austria",
      image: img7,
      description: "Чудова квартира з усіма необхідними зручностями.",
      price: "320$ за три доби",
    },
    {
      name: "Adagio Downtown MiniHotel",
      location: "Baku, Azerbaijan",
      rating: 8.8,
      category: "hotel",
      type: "offering",
      country: "Azerbaijan",
      image: img8,
      description: "Чудова квартира з усіма необхідними зручностями.",
      price: "320$ за три доби",
    },
    {
      name: "Benczur Hotel",
      location: "Kraków, Poland",
      rating: 5.5,
      category: "hotel",
      type: "offering",
      country: "Poland",
      image: img9,
      description: "Чудова квартира з усіма необхідними зручностями.",
      price: "320$ за три доби",
    },
    {
      name: "Easy Star Hotel",
      location: "Andresen, Portugal",
      rating: 4.8,
      category: "hotel",
      type: "offering",
      country: "Portugal",
      image: img10,
      description: "Чудова квартира з усіма необхідними зручностями.",
      price: "320$ за три доби",
    },
    {
      name: "Silver Hotel",
      location: "Petrou Karakousi, Greece",
      rating: 7.4,
      category: "hotel",
      type: "offering",
      country: "Greece",
      image: img11,
      description: "Чудова квартира з усіма необхідними зручностями.",
      price: "320$ за три доби",
    },
    {
      name: "Erzsébet",
      location: "Alicante, Spain",
      rating: 6.2,
      category: "hotel",
      type: "offering",
      country: "Spain",
      image: img12,
      description: "Чудова квартира з усіма необхідними зручностями.",
      price: "320$ за три доби",
    },
    {
      name: "KVIHotel",
      location: "Madrid, Spain",
      rating: 7.2,
      category: "hotel",
      type: "offering",
      country: "Spain",
      image: img13,
      description: "Чудова квартира з усіма необхідними зручностями.",
      price: "320$ за три доби",
    },
    {
      name: "Petit Hotel",
      location: "Madrid, Spain",
      rating: 7.2,
      category: "hotel",
      type: "offering",
      country: "Spain",
      image: img14,
      description: "Чудова квартира з усіма необхідними зручностями.",
      price: "320$ за три доби",
    },
    {
      name: "Le Galion Hotel",
      location: "Saint-Martin-de-Ré, France",
      rating: 8.4,
      category: "hotel",
      type: "offering",
      country: "France",
      image: img15,
      description: "Чудова квартира з усіма необхідними зручностями.",
      price: "320$ за три доби",
    },
    {
      name: "Vila Gale Lagos Hotel",
      location: "Andresen, Portugal",
      rating: 7.1,
      category: "hotel",
      type: "offering",
      country: "Portugal",
      image: img16,
      description: "Чудова квартира з усіма необхідними зручностями.",
      price: "320$ за три доби",
    },
  ]

const advertSlice = createSlice({
    name: "advert",
    initialState,
    reducers: {
        
    }
})

export const advertReducer =  advertSlice.reducer